# -*- coding: utf-8 -*-
"""
/***************************************************************************
 new_raptor
                                 A QGIS plugin
 The "Add New Raptor" plugin is a powerful tool designed to streamline the process of adding new features to your QGIS layers. Specifically crafted for users working with geospatial data, this plugin facilitates the addition of a new Raptor feature to existing layers with ease.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-03-02
        copyright            : (C) 2024 by TJ Fitzpatrick
        email                : tjfitzster@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load new_raptor class from file new_raptor.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .newRaptor import new_raptor
    return new_raptor(iface)
